import { StyleSheet } from 'react-native';
import theme from '../../../ theme';

const styles = StyleSheet.create({
    container: {
        flex: 1,
        alignItems: 'center',
        padding: 20,
    },
    selectedFileText: {
        marginTop: 10,
        fontSize: 16,
        fontFamily: theme.fonts.bold,
    },
    errorText: {
        color: 'red',
        marginTop: 10,
    },
    transcriptionContainer: {
        marginTop: 10,
        padding: 10,
        borderWidth: 0,
        borderRadius: 5,
        backgroundColor: theme.colors.diff,
        width: "100%",
    },
    transcriptionActions: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "flex-end",
        gap: 10,
    },
    transcribedText: {
        fontSize: 16,
        fontFamily: theme.fonts.regular,
    },
    copyButton: {
        marginTop: 10,
        backgroundColor: theme.colors.primary,
        padding: 10,
        borderRadius: 5,
        display: "flex",
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        width: 40,
    },
    copyButtonText: {
        color: 'white',
    },
    uploadButton: {
        backgroundColor: "transparent",
        paddingVertical: 10,
        paddingHorizontal: 25,
        borderRadius: 15,
        alignItems: "center",
        borderWidth: 1,
        borderColor: theme.colors.secondary,
        display: "flex",
        flexDirection: "row",
        gap: 10,
    },
    uploadButtonText: {
        color: theme.colors.secondary,
        fontSize: 16,
        fontWeight: "bold",
        fontFamily: theme.fonts.bold,
    },
    selectedFileContainer: {
        marginTop: 10,
        gap: 10,
        alignItems: "center",
        padding: 10,
        borderWidth: 0,
        borderRadius: 10,
    },
    audioRecorderContainer: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        gap: 40,
    },
    audioPreview: {
        marginTop: 15,
        width: "100%",
        padding: 10,
        backgroundColor: theme.colors.diff,
        borderRadius: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },

    playButton: {
        backgroundColor: theme.colors.primary,
        borderRadius: 50,
        alignItems: "center",
        justifyContent: "center",
        display: "flex",
        width: 40,
        height: 40,
    },
    modalContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: "rgba(255, 244, 194, 0.39)",
        padding: 20,
    },
    modalTitle: {
        fontSize: 20,
        fontFamily: theme.fonts.bold,
        marginBottom: 20,
    },
    modalInput: {
        width: '100%',
        height: 50,
        borderColor: theme.colors.lightYellowShade,
        borderWidth: 1,
        borderRadius: 10,
        padding: 10,
        marginBottom: 20,
        fontSize: 16,
        fontFamily: theme.fonts.regular,
        backgroundColor: theme.colors.background,
    },
    modalContent: {
        width: '100%',
        backgroundColor: theme.colors.background,
        borderRadius: 10,
        padding: 20,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: theme.colors.primary,
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 4,
        elevation: 5,
    },
    modalButtons: {
        display: "flex",
        flexDirection: "row",
        justifyContent: "space-between",
        width: "100%",
        marginTop: 20,
        gap: 20,
        padding: 10,
        borderWidth: 0,
        borderRadius: 10,
        backgroundColor: theme.colors.background,
    },
    cancelButton: {
        backgroundColor: theme.colors.secondary,
        padding: 10,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        display: "flex",
        width: "45%",
        height: 50,
        color: "#fff",
        borderColor: theme.colors.lightYellowShade,
        borderWidth: 2,
    },
    saveConfirmButton: {
        backgroundColor: theme.colors.primary,
        padding: 10,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
        display: "flex",
        width: "45%",
        height: 50,
        color: "#fff",
        borderColor: "#BFD7EA",
        borderWidth: 2,
    },
    cancelBtnText: {
        color: "#fff",
        fontSize: 16,
        fontFamily: theme.fonts.bold,
    },
    saveBtnText: {
        color: "#fff",
        fontSize: 16,
        fontFamily: theme.fonts.bold,
    },
});

export default styles;
